networks:
  roboshop:
    driver: bridge
services:
  mongodb: 
   image: mongodb:v1
   container_name: mongodb
   networks:
   - roboshop
  catalogue:
   image: catalogue:v1
   container_image: catalogue
   networks:
   - robsohop
   depends_on:
   - mongodb
  reddis:
   image: reddis:v1
   container_name: reddis
   networks:
   - roboshop
  user:
   image: user:v1
   container_name: user
   networks:
   - roboshop
   depends_on:
   - mongodb
   - reddis
  web:
   image: web:v1
   container_name: web
   networks:
    - roboshop
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
   
  