networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    networks:
      - roboshop
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    networks:
      - roboshop
      depends_on:
      - mongodb
  redis:
    image: redis:v1
    container_name: redis
    networks:
      - robsohop
  user:
    image: user:v1
    container_name: user
    networks:
      - robsohop

  web:
    image: web:v1
    conatiner_name: web
    networks:
      - roboshop
      ports:
      - "80:80"
      depends_on:
      - catalogue
      - user



